### ISSUE TITLE
Use EJSON for serialization.

### ISSUE THREAD

**Issue by luzlab** [StrictlySkyler/elytron#1]
It would be great to be able to stringify and parse messages with EJSON. I can submit a PR if you'd like.

**Comment by strictlyskyler** [comment]
This may no longer be necessary; with `2.0.0`, you should be able to just use text as an interface, and leverage EJSON within your app itself.  What's the use-case?

**Comment by luzlab** [comment]
yeah... I can handle EJSON.stringify/parse on my own.

**Comment by strictlyskyler** [comment]
Groovy.  I'll close this then.  :-)
